services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: gameengine-sql
    ports:
      - "5050:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${SA_PASSWORD}"
      MSSQL_PID: "Developer"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  sqlserver_data:
