//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CF.Identity.Infrastructure.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CF.Identity.Infrastructure.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access token read.
        /// </summary>
        internal static string AccessTokenReadRoleName {
            get {
                return ResourceManager.GetString("AccessTokenReadRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User can add, update or delete access tokens.
        /// </summary>
        internal static string AccessTokenWriteRoleDescription {
            get {
                return ResourceManager.GetString("AccessTokenWriteRoleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access token write.
        /// </summary>
        internal static string AccessTokenWriteRoleName {
            get {
                return ResourceManager.GetString("AccessTokenWriteRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User can read clients.
        /// </summary>
        internal static string ClientReadRoleDescription {
            get {
                return ResourceManager.GetString("ClientReadRoleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client read.
        /// </summary>
        internal static string ClientReadRoleName {
            get {
                return ResourceManager.GetString("ClientReadRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client can add, update or delete access tokens.
        /// </summary>
        internal static string ClientWriteRoleDescription {
            get {
                return ResourceManager.GetString("ClientWriteRoleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client write.
        /// </summary>
        internal static string ClientWriteRoleName {
            get {
                return ResourceManager.GetString("ClientWriteRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User can read roles.
        /// </summary>
        internal static string RoleReadRoleDescription {
            get {
                return ResourceManager.GetString("RoleReadRoleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role read.
        /// </summary>
        internal static string RoleReadRoleName {
            get {
                return ResourceManager.GetString("RoleReadRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User can add, update or delete roles.
        /// </summary>
        internal static string RoleWriteRoleDescription {
            get {
                return ResourceManager.GetString("RoleWriteRoleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role write.
        /// </summary>
        internal static string RoleWriteRoleName {
            get {
                return ResourceManager.GetString("RoleWriteRoleName", resourceCulture);
            }
        }
    }
}
